### ISSUE TITLE
ModuleNotFoundError

### ISSUE THREAD

**Issue by kmein** [syrusakbary/gdom#12]
When I run gdom I get this output:

```
Traceback (most recent call last):
  File "/home/kfm/.local/bin/gdom", line 7, in <module>
    from gdom.cmd import main
  File "/home/kfm/.local/lib/python3.6/site-packages/gdom/cmd.py", line 9, in <module>
    from schema import schema
ModuleNotFoundError: No module named 'schema'
```

It seems to be a problem with gdom itself, somehow not finding its own [ schema.py](https://github.com/syrusakbary/gdom/blob/master/gdom/schema.py). Any idea what's going wrong there and how to fix this?

**Comment by babakness** [comment]
same

**Comment by babakness** [comment]
I'm not really a python guy but a simple hack is to change the `cmd.py` file. Instead of 

`from schema import schema`

do 

`from gdom.schema import schema`

I believe some kind of environment issue caused by how the `/usr/bin/local/gdom` file is written.

**Comment by wis** [comment]
can confirm also, when installing with pip and `--user` and with pipenv. and @babakness's solution fixed the issue when I modified `~/.local/share/virtualenvs/testgdom/lib/python3.7/sites-packages/gdom/cmd.py` (`testgdom` is the name of the project/pipenv directory)

**Comment by wis** [comment]
can also confirm, when installing with pip and `--user` and with pipenv. and @babakness's solution fixed the issue when I modified `~/.local/share/virtualenvs/testgdom/lib/python3.7/sites-packages/gdom/cmd.py` (`testgdom` is the name of the project/pipenv directory)
