### ISSUE TITLE
ImportError: No module named core.execution.executor

### ISSUE THREAD

**Issue by BarryBaum** [syrusakbary/gdom#7]
I was testing a fresh install of the module and ran a gdom --test   resulting in the following traceback: 

```

Traceback (most recent call last):
  File "/usr/local/bin/gdom", line 7, in <module>
    from gdom.cmd import main
  File "/usr/local/lib/python2.7/site-packages/gdom/__init__.py", line 1, in <module>
    from .schema import schema, Node, Element, Document, Query
  File "/usr/local/lib/python2.7/site-packages/gdom/schema.py", line 1, in <module>
    import graphene
  File "/usr/local/lib/python2.7/site-packages/graphene/__init__.py", line 3, in <module>
    from .core import (
  File "/usr/local/lib/python2.7/site-packages/graphene/core/__init__.py", line 1, in <module>
    from .schema import (
  File "/usr/local/lib/python2.7/site-packages/graphene/core/schema.py", line 4, in <module>
    from graphql.core.execution.executor import Executor
ImportError: No module named core.execution.executor
```

Below is my python installation log: 

https://gist.github.com/dca2f5c358b1aa7de3093565b8fad874

**Comment by BarryBaum** [comment]
found the cause,  looks like PyPy is not bringing in the correct version.  
you need to install from github using pip install git+git   or clone and install local.

**Comment by amsimoes** [comment]
To give more details to the solution (using pip for python2.7):

`sudo pip install git+https://github.com/syrusakbary/gdom.git`

**Comment by mrVanDalo** [comment]
@BarryBaum try the docker container : https://hub.docker.com/r/palo/gdom/
