### ISSUE TITLE
Cant Run

### ISSUE THREAD

**Issue by idkjs** [syrusakbary/gdom#9]
Hi. Figured I would learn something about dom nodes by using this. I cant get the project to run though. I installed with pip3 install gdom on a mac.

i get the following error. I dont know if this is something a seasoned python dev would know how to deal with. I dont know any python...yet.

error is:

```
$ gdom --test
Traceback (most recent call last):
  File "/usr/local/bin/gdom", line 7, in <module>
    from gdom.cmd import main
  File "/usr/local/lib/python3.6/site-packages/gdom/__init__.py", line 1, in <module>
    from .schema import schema, Node, Element, Document, Query
  File "/usr/local/lib/python3.6/site-packages/gdom/schema.py", line 1, in <module>
    import graphene
  File "/usr/local/lib/python3.6/site-packages/graphene/__init__.py", line 3, in <module>
    from .core import (
  File "/usr/local/lib/python3.6/site-packages/graphene/core/__init__.py", line 1, in <module>
    from .schema import (
  File "/usr/local/lib/python3.6/site-packages/graphene/core/schema.py", line 4, in <module>
    from graphql.core.execution.executor import Executor
ModuleNotFoundError: No module named 'graphql.core'
```

Thanks.

**Comment by syrusakbary** [comment]
This should be fixed now.
A new version `1.0.0` is available in PyPI.

If this issue keeps happening, try with `pip uninstall graphql-core` and then `pip install gdom`.

**Comment by idkjs** [comment]
Followed the instructions, same result:
```sh
$ gdom --test
Traceback (most recent call last):
  File "/usr/local/bin/gdom", line 7, in <module>
    from gdom.cmd import main
  File "/usr/local/lib/python3.6/site-packages/gdom/__init__.py", line 1, in <module>
    from .schema import schema, Node, Element, Document, Query
  File "/usr/local/lib/python3.6/site-packages/gdom/schema.py", line 1, in <module>
    import graphene
  File "/usr/local/lib/python3.6/site-packages/graphene/__init__.py", line 3, in <module>
    from .core import (
  File "/usr/local/lib/python3.6/site-packages/graphene/core/__init__.py", line 1, in <module>
    from .schema import (
  File "/usr/local/lib/python3.6/site-packages/graphene/core/schema.py", line 4, in <module>
    from graphql.core.execution.executor import Executor
ModuleNotFoundError: No module named 'graphql.core'
```

**Comment by syrusakbary** [comment]
Hi @idkjs it seems you have a very old version of graphene running.

You can try also with `pip install "graphene>=2.0.1"`.
If this doesn't solve it, might be useful to see the output from running this in python:
```python
import graphene
print(graphene.__version__)
```

**Comment by idkjs** [comment]
Don't even know if i did this right. node/reason guy here.

```sh
$ python
Python 2.7.13 (default, Sep 14 2017, 23:31:37)
[GCC 4.2.1 Compatible Apple LLVM 9.0.0 (clang-900.0.37)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import graphene
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: No module named graphene
>>> import graphene
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: No module named graphene
>>> print(graphene.__version__)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
NameError: name 'graphene' is not defined
>>> exit
Use exit() or Ctrl-D (i.e. EOF) to exit
>>>
^[[A

shingdev at cosmos in ~/code/REASON/hackjam-reason-react-master
$ python3
Python 3.6.2 (default, Sep  8 2017, 18:08:28)
[GCC 4.2.1 Compatible Apple LLVM 9.0.0 (clang-900.0.35)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import graphene
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.6/site-packages/graphene/__init__.py", line 3, in <module>
    from .core import (
  File "/usr/local/lib/python3.6/site-packages/graphene/core/__init__.py", line 1, in <module>
    from .schema import (
  File "/usr/local/lib/python3.6/site-packages/graphene/core/schema.py", line 4, in <module>
    from graphql.core.execution.executor import Executor
ModuleNotFoundError: No module named 'graphql.core'
>>> print(graphene.__version__)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
NameError: name 'graphene' is not defined
>>>
```

- two versions of python installed so figured try to install graphene gdom w/ pip3:

```sh
$ pip3 install gdom graphene
Requirement already satisfied: gdom in /usr/local/lib/python3.6/site-packages
Requirement already satisfied: graphene in /usr/local/lib/python3.6/site-packages
Requirement already satisfied: requests==2.9.1 in /usr/local/lib/python3.6/site-packages (from gdom)
Requirement already satisfied: flask-graphql==1.1.0 in /usr/local/lib/python3.6/site-packages (from gdom)
Requirement already satisfied: pyquery==1.2.11 in /usr/local/lib/python3.6/site-packages (from gdom)
Requirement already satisfied: graphql-relay==0.3.3 in /usr/local/lib/python3.6/site-packages (from graphene)
Requirement already satisfied: graphql-core>=0.4.9 in /usr/local/lib/python3.6/site-packages (from graphene)
Requirement already satisfied: six>=1.10.0 in /usr/local/lib/python3.6/site-packages (from graphene)
Requirement already satisfied: flask>=0.7.0 in /usr/local/lib/python3.6/site-packages (from flask-graphql==1.1.0->gdom)
Requirement already satisfied: lxml>=2.1 in /usr/local/lib/python3.6/site-packages (from pyquery==1.2.11->gdom)
Requirement already satisfied: cssselect>0.7.9 in /usr/local/lib/python3.6/site-packages (from pyquery==1.2.11->gdom)
Requirement already satisfied: promise>=2.0 in /usr/local/lib/python3.6/site-packages (from graphql-core>=0.4.9->graphene)
Requirement already satisfied: itsdangerous>=0.21 in /usr/local/lib/python3.6/site-packages (from flask>=0.7.0->flask-graphql==1.1.0->gdom)
Requirement already satisfied: Werkzeug>=0.7 in /usr/local/lib/python3.6/site-packages (from flask>=0.7.0->flask-graphql==1.1.0->gdom)
Requirement already satisfied: Jinja2>=2.4 in /usr/local/lib/python3.6/site-packages (from flask>=0.7.0->flask-graphql==1.1.0->gdom)
Requirement already satisfied: click>=2.0 in /usr/local/lib/python3.6/site-packages (from flask>=0.7.0->flask-graphql==1.1.0->gdom)
Requirement already satisfied: typing in /usr/local/lib/python3.6/site-packages (from promise>=2.0->graphql-core>=0.4.9->graphene)
Requirement already satisfied: MarkupSafe>=0.23 in /usr/local/lib/python3.6/site-packages (from Jinja2>=2.4->flask>=0.7.0->flask-graphql==1.1.0->gdom)
```

- then ran gdom --test again. Looks like its looking for `graphql.core`  instead of listed `graphql-core`

```sh
$ gdom --test
Traceback (most recent call last):
  File "/usr/local/bin/gdom", line 7, in <module>
    from gdom.cmd import main
  File "/usr/local/lib/python3.6/site-packages/gdom/__init__.py", line 1, in <module>
    from .schema import schema, Node, Element, Document, Query
  File "/usr/local/lib/python3.6/site-packages/gdom/schema.py", line 1, in <module>
    import graphene
  File "/usr/local/lib/python3.6/site-packages/graphene/__init__.py", line 3, in <module>
    from .core import (
  File "/usr/local/lib/python3.6/site-packages/graphene/core/__init__.py", line 1, in <module>
    from .schema import (
  File "/usr/local/lib/python3.6/site-packages/graphene/core/schema.py", line 4, in <module>
    from graphql.core.execution.executor import Executor
ModuleNotFoundError: No module named 'graphql.core'
```
